import { prisma } from "@/lib/prisma";

export type SupplierChannel = "marketplace" | "official-store" | "publisher-store" | "affiliate-network";
export type SupplierIntegration =
  | "active-api"
  | "cheapshark"
  | "affiliate-feed-ready"
  | "needs-credentials"
  | "manual-review";

export type SupplierCatalogEntry = {
  name: string;
  slug: string;
  website: string;
  channel: SupplierChannel;
  integration: SupplierIntegration;
  priority: "core" | "high" | "medium";
  feedEnv?: string;
  rating?: number;
  verified: boolean;
  description: string;
};

export const supplierCatalog: SupplierCatalogEntry[] = [
  {
    name: "Kinguin",
    slug: "kinguin",
    website: "https://www.kinguin.net",
    channel: "marketplace",
    integration: "active-api",
    priority: "core",
    rating: 4.3,
    verified: true,
    description: "Direkte Kinguin eCommerce API ist aktiv.",
  },
  {
    name: "Eneba",
    slug: "eneba",
    website: "https://www.eneba.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "core",
    feedEnv: "ENEBA_FEED_URL",
    rating: 4.2,
    verified: true,
    description: "Affiliate/API-Feed vorbereitet; Feed-URL/Zugangsdaten fehlen noch.",
  },
  {
    name: "G2A",
    slug: "g2a",
    website: "https://www.g2a.com",
    channel: "marketplace",
    integration: "needs-credentials",
    priority: "core",
    feedEnv: "G2A_FEED_URL",
    rating: 4.0,
    verified: true,
    description: "G2A Export/Integration API braucht Partnerzugang.",
  },
  {
    name: "GAMIVO",
    slug: "gamivo",
    website: "https://www.gamivo.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "core",
    feedEnv: "GAMIVO_FEED_URL",
    rating: 4.1,
    verified: true,
    description: "AWIN/Admitad/CJ/Partnerize-Feed vorbereitet.",
  },
  {
    name: "MMOGA",
    slug: "mmoga",
    website: "https://www.mmoga.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "core",
    feedEnv: "MMOGA_FEED_URL",
    rating: 4.0,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "Loaded / CDKeys",
    slug: "loaded-cdkeys",
    website: "https://www.loaded.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "core",
    feedEnv: "LOADED_FEED_URL",
    rating: 4.3,
    verified: true,
    description: "CDKeys ist als Loaded weitergefuehrt; Affiliate-Feed vorbereitet.",
  },
  {
    name: "Instant Gaming",
    slug: "instant-gaming",
    website: "https://www.instant-gaming.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "core",
    feedEnv: "INSTANT_GAMING_FEED_URL",
    rating: 4.2,
    verified: true,
    description: "Partner-/Affiliate-Feed vorbereitet.",
  },
  {
    name: "HRKGame",
    slug: "hrkgame",
    website: "https://www.hrkgame.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "high",
    feedEnv: "HRKGAME_FEED_URL",
    rating: 3.9,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "K4G",
    slug: "k4g",
    website: "https://k4g.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "high",
    feedEnv: "K4G_FEED_URL",
    rating: 3.9,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "Driffle",
    slug: "driffle",
    website: "https://driffle.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "high",
    feedEnv: "DRIFFLE_FEED_URL",
    rating: 3.9,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "Difmark",
    slug: "difmark",
    website: "https://difmark.com",
    channel: "marketplace",
    integration: "manual-review",
    priority: "medium",
    feedEnv: "DIFMARK_FEED_URL",
    rating: 3.6,
    verified: false,
    description: "Nur nach Qualitaetspruefung aktivieren.",
  },
  {
    name: "RoyalCDKeys",
    slug: "royalcdkeys",
    website: "https://royalcdkeys.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "medium",
    feedEnv: "ROYALCDKEYS_FEED_URL",
    rating: 3.8,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "CJS CD Keys",
    slug: "cjs-cd-keys",
    website: "https://www.cjs-cdkeys.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "medium",
    feedEnv: "CJS_CD_KEYS_FEED_URL",
    rating: 3.7,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "SCDKey",
    slug: "scdkey",
    website: "https://www.scdkey.com",
    channel: "marketplace",
    integration: "affiliate-feed-ready",
    priority: "medium",
    feedEnv: "SCDKEY_FEED_URL",
    rating: 3.7,
    verified: true,
    description: "Affiliate-Feed vorbereitet.",
  },
  {
    name: "GVGmall",
    slug: "gvgmall",
    website: "https://www.gvgmall.com",
    channel: "marketplace",
    integration: "manual-review",
    priority: "medium",
    feedEnv: "GVGMALL_FEED_URL",
    rating: 3.5,
    verified: false,
    description: "Nur nach Qualitaetspruefung aktivieren.",
  },
  {
    name: "Fanatical",
    slug: "fanatical",
    website: "https://www.fanatical.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "core",
    rating: 4.6,
    verified: true,
    description: "Ueber CheapShark abgedeckt; Affiliate-Feed optional.",
  },
  {
    name: "Green Man Gaming",
    slug: "greenmangaming",
    website: "https://www.greenmangaming.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "core",
    rating: 4.5,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Gamesplanet",
    slug: "gamesplanet",
    website: "https://www.gamesplanet.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "core",
    rating: 4.5,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "GameBillet",
    slug: "gamebillet",
    website: "https://www.gamebillet.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "high",
    rating: 4.4,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Humble Store",
    slug: "humble-store",
    website: "https://www.humblebundle.com/store",
    channel: "official-store",
    integration: "cheapshark",
    priority: "high",
    rating: 4.5,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "GOG",
    slug: "gog",
    website: "https://www.gog.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "high",
    rating: 4.6,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Steam",
    slug: "steam",
    website: "https://store.steampowered.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "high",
    rating: 4.6,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Epic Games Store",
    slug: "epic",
    website: "https://store.epicgames.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "high",
    rating: 4.3,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "GamersGate",
    slug: "gamersgate",
    website: "https://www.gamersgate.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.2,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Voidu",
    slug: "voidu",
    website: "https://www.voidu.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.1,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "IndieGala",
    slug: "indiegala",
    website: "https://www.indiegala.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.0,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "DLGamer",
    slug: "dlgamer",
    website: "https://www.dlgamer.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.0,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Noctre",
    slug: "noctre",
    website: "https://www.noctre.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.0,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "DreamGame",
    slug: "dreamgame",
    website: "https://www.dreamgame.com",
    channel: "official-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.0,
    verified: true,
    description: "Ueber CheapShark abgedeckt.",
  },
  {
    name: "Ubisoft Store",
    slug: "ubisoft-store",
    website: "https://store.ubisoft.com",
    channel: "publisher-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.1,
    verified: true,
    description: "Teilweise ueber CheapShark/Uplay abgedeckt.",
  },
  {
    name: "EA app / Origin",
    slug: "ea-origin",
    website: "https://www.ea.com",
    channel: "publisher-store",
    integration: "cheapshark",
    priority: "medium",
    rating: 4.0,
    verified: true,
    description: "Teilweise ueber CheapShark/Origin abgedeckt.",
  },
  {
    name: "Microsoft Store / Xbox",
    slug: "microsoft-xbox",
    website: "https://www.xbox.com",
    channel: "publisher-store",
    integration: "affiliate-feed-ready",
    priority: "medium",
    feedEnv: "MICROSOFT_XBOX_FEED_URL",
    rating: 4.2,
    verified: true,
    description: "Affiliate-Feed vorbereitet; keine Gift-Card-Produkte in Top-Deals.",
  },
  {
    name: "PlayStation Store",
    slug: "playstation-store",
    website: "https://store.playstation.com",
    channel: "publisher-store",
    integration: "affiliate-feed-ready",
    priority: "medium",
    feedEnv: "PLAYSTATION_FEED_URL",
    rating: 4.2,
    verified: true,
    description: "Affiliate-Feed vorbereitet; keine Wallet-Produkte in Top-Deals.",
  },
  {
    name: "Nintendo eShop",
    slug: "nintendo-eshop",
    website: "https://www.nintendo.com/store",
    channel: "publisher-store",
    integration: "affiliate-feed-ready",
    priority: "medium",
    feedEnv: "NINTENDO_FEED_URL",
    rating: 4.2,
    verified: true,
    description: "Affiliate-Feed vorbereitet; keine eShop-Cards in Top-Deals.",
  },
];

export function getSupplierBySlug(slug: string) {
  return supplierCatalog.find((supplier) => supplier.slug === slug);
}

export function getSupplierByName(name: string) {
  const normalized = name.toLowerCase();
  return supplierCatalog.find((supplier) => supplier.name.toLowerCase() === normalized);
}

export function getConfiguredSupplierFeedEnvs() {
  return supplierCatalog.filter((supplier) => supplier.feedEnv);
}

export async function syncSupplierCatalog() {
  let createdOrUpdated = 0;

  for (const supplier of supplierCatalog) {
    await prisma.store.upsert({
      where: { slug: supplier.slug },
      update: {
        name: supplier.name,
        url: supplier.website,
        website: supplier.website,
        isVerified: supplier.verified,
        rating: supplier.rating,
        description: supplier.description,
      },
      create: {
        name: supplier.name,
        slug: supplier.slug,
        url: supplier.website,
        website: supplier.website,
        isVerified: supplier.verified,
        rating: supplier.rating,
        paymentMethods: [],
        description: supplier.description,
      },
    });
    createdOrUpdated++;
  }

  return { ok: true, suppliers: createdOrUpdated };
}
